# Wprowadzenie

[Formatowanie markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb#scrollTo=Lhfnlq1Surtk)

## Pandas - co to w ogóle jest?
Pandas to **biblioteka** niezbędna do **analizy danych** w Pythonie. Dostarcza wydajne struktury danych, dzięki którym praca z danymi tabelarycznymi staje się prosta i intuicyjna. Celem twórców jest utrzymanie statusu biblioteki niezbędnej do codziennych analiz oraz zdobycie fotela lidera w kategorii najpotężniejszego narzędzia open-source do analizy danych w jakimkolwiek języku programowania. Obecnie, projekt wciąż prężnie się rozwija i jego znajomość jest niezbędna dla każdego data scientista.

[Dokumentacja pandas](https://pandas.pydata.org/docs/)

## Pandas - kiedy stosować?
Pandas będzie dobrym wyborem do następujących zastosowań:
- Dane tabelaryczne (kolumny jak w SQLu lub Excelu)
- Dane reprezentujące szeregi czasowe
- Macierze
- Wyniki pomiarów i statystyk

## Pandas - struktury danych

- **Series** to **jednowymiarowa** struktura danych (jednowymiarowa macierz
numpy), która oprócz danych przechowuje też unikalny indeks.\
Seria jest bardzo podobna do tablicy NumPy (w rzeczywistości jest zbudowana na obiekcie tablicy NumPy). To, co odróżnia tablicę NumPy od serii, to fakt, że seria może mieć etykiety osi, co oznacza, że ​​może być indeksowana etykietą, a nie tylko lokalizacją liczbową. Nie musi również przechowywać danych liczbowych, może przechowywać dowolny obiekt Pythona.\
Tworzenie: *pd.Series(zawartosc)*

- Drugą strukturą w pandas jest **DataFrame** (ramki danych) - czyli **dwu** lub **więcej wymiarowa** struktura danych, najczęściej w formie tabeli z wierszami i kolumnami.\
  **Kolumny** mają **nazwy**, a **wiersze** mają **indeksy**.\
Tworzenie: *pd.DataFrame(zawartosc)*

## Biblioteki

In [ ]:
import pandas as pd
import numpy as np

# Series

In [ ]:
# z listy
labels = ['a','b','c']
my_list = [10,20,30]

pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
# z tablicy
arr = np.array([10,20,30])
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(arr, index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
# ze słowniak
d = {'a':10,'b':20,'c':30}

pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [ ]:
# z krotki(tuple)
k = (1.1,2.1,3)
pd.Series(k)

0    1.1
1    2.1
2    3.0
dtype: float64

In [ ]:
#losowe liczby z zakresu [0,1)
pd.Series(np.random.rand(10))

0    0.784226
1    0.224712
2    0.479235
3    0.282935
4    0.715609
5    0.216641
6    0.625380
7    0.734035
8    0.289401
9    0.125536
dtype: float64

In [ ]:
pd.Series([1,2,3,np.nan, 4,5, np.nan])

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
6    NaN
dtype: float64

## Korzystanie z indeksu
Kluczem do korzystania z serii jest zrozumienie jej indeksu. Pandas wykorzystuje te nazwy indeksów lub numery, umożliwiając szybkie wyszukiwanie informacji (działa jak tablica skrótów lub słownik).\
Zobaczmy kilka przykładów, jak pobierać informacje z serii. Utwórzmy dwa sereis, ser1 i ser2:

In [ ]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [ ]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [ ]:
ser2['Italy']

np.int64(5)

In [ ]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

# Data Frame

Ramki danych (DataFrame) są koniem pociągowym biblioteki pandas i zostały bezpośrednio zainspirowane językiem programowania R. Możemy myśleć o ramce danych jako o zestawie obiektów typu Series, które zostały połączone tak, aby dzieliły ten sam indeks.

In [ ]:
df=pd.DataFrame(np.random.randn(6,4), columns=list('ABCD')) # 6 - wierszy i 4 kolumny z losowymi liczbami
df

          A         B         C         D
0 -0.709755  0.856705 -0.368135 -1.989980
1  0.204816 -0.800375 -0.430083 -0.495844
2 -0.739421 -0.606702 -2.364269 -0.964341
3 -0.724366 -0.933328  0.064789  0.387952
4  1.489746 -0.215920 -0.221706  2.580736
5 -0.878342 -0.065532  0.154765 -2.028897

In [ ]:
df=pd.DataFrame(np.random.randn(5,4), columns=['A', 'B', 'C', 'D'], index=['W0', 'W1', 'W2', 'W3', 'W4']) # 5 - wierszy i 4 kolumny z losowymi liczbami
df

           A         B         C         D
W0 -1.464134  1.239321  0.121756  0.131893
W1 -0.219985  0.676829  0.584892 -0.405147
W2  0.482510 -1.181670  1.633778 -2.511288
W3 -1.511729  0.025677  0.373815 -0.811521
W4 -0.620976 -1.779730 -0.340072 -1.737196

In [ ]:
# z zagnieżdżonej listy (list of lists)
lista2 = [['Ania', 30], ['Zosia', 60], ['Krysia', 15], ['Jola', 40]]
lista2

[['Ania', 30], ['Zosia', 60], ['Krysia', 15], ['Jola', 40]]

In [ ]:
pd.DataFrame(lista2, columns=['Imie', 'Wiek'])

     Imie  Wiek
0    Ania    30
1   Zosia    60
2  Krysia    15
3    Jola    40

In [ ]:
pd.DataFrame(lista2, columns=['Imie', 'Wiek'], index = ['AA', 'ZZ', 'KK', 'JJ'])

      Imie  Wiek
AA    Ania    30
ZZ   Zosia    60
KK  Krysia    15
JJ    Jola    40

In [ ]:
# DF ze słownika (dictionary)
slownik1 = {'Name': ['Paweł', 'Piorek', 'Karol'],
            'Age': [30, 40, 50]}
slownik1

{'Name': ['Paweł', 'Piorek', 'Karol'], 'Age': [30, 40, 50]}

In [ ]:
pd.DataFrame(slownik1)

     Name  Age
0   Paweł   30
1  Piorek   40
2   Karol   50

## Wybiranie i indeksowanie

In [ ]:
df

           A         B         C         D
W0 -1.464134  1.239321  0.121756  0.131893
W1 -0.219985  0.676829  0.584892 -0.405147
W2  0.482510 -1.181670  1.633778 -2.511288
W3 -1.511729  0.025677  0.373815 -0.811521
W4 -0.620976 -1.779730 -0.340072 -1.737196

In [ ]:
# po nazwie kolumny / kolumn
df['B']

W0    1.239321
W1    0.676829
W2   -1.181670
W3    0.025677
W4   -1.779730
Name: B, dtype: float64

In [ ]:
df[['A', 'C']]

           A         C
W0 -1.464134  0.121756
W1 -0.219985  0.584892
W2  0.482510  1.633778
W3 -1.511729  0.373815
W4 -0.620976 -0.340072

In [ ]:
type(df[['B']])

pandas.core.frame.DataFrame

In [ ]:
type(df[['B']])

pandas.core.frame.DataFrame

### LOC i ILOC
iloc - odnosił do nr wiersza/kolumny\
loc - odnosił do nazwy wiersza/kolumny

In [ ]:
df

           A         B         C         D
W0 -1.464134  1.239321  0.121756  0.131893
W1 -0.219985  0.676829  0.584892 -0.405147
W2  0.482510 -1.181670  1.633778 -2.511288
W3 -1.511729  0.025677  0.373815 -0.811521
W4 -0.620976 -1.779730 -0.340072 -1.737196

In [ ]:
df.loc['W1']

A   -0.219985
B    0.676829
C    0.584892
D   -0.405147
Name: W1, dtype: float64

In [ ]:
df.iloc[1]

A   -0.219985
B    0.676829
C    0.584892
D   -0.405147
Name: W1, dtype: float64

In [ ]:
df.loc['W1', ['B', 'C']]

B    0.676829
C    0.584892
Name: W1, dtype: float64

In [ ]:
df.iloc[:2, :2]

           A         B
W0 -1.464134  1.239321
W1 -0.219985  0.676829

### Warunkowe wybieranie

In [ ]:
df

           A         B         C         D
W0 -1.464134  1.239321  0.121756  0.131893
W1 -0.219985  0.676829  0.584892 -0.405147
W2  0.482510 -1.181670  1.633778 -2.511288
W3 -1.511729  0.025677  0.373815 -0.811521
W4 -0.620976 -1.779730 -0.340072 -1.737196

In [ ]:
df>0

        A      B      C      D
W0  False   True   True   True
W1  False   True   True  False
W2   True  False   True  False
W3  False   True   True  False
W4  False  False  False  False

In [ ]:
df[df>0]

          A         B         C         D
W0      NaN  1.239321  0.121756  0.131893
W1      NaN  0.676829  0.584892       NaN
W2  0.48251       NaN  1.633778       NaN
W3      NaN  0.025677  0.373815       NaN
W4      NaN       NaN       NaN       NaN

In [ ]:
df[df['A']>0]

          A        B         C         D
W2  0.48251 -1.18167  1.633778 -2.511288

In [ ]:
df[df['A']>0]['B'] # wyświetli te lementy kolumny B, dla których w A został spełniony warunek

W2   -1.18167
Name: B, dtype: float64

In [ ]:
df[(df['A']<0) & (df['B'] > 0)]['C'] #łączenie warunków

W0    0.121756
W1    0.584892
W3    0.373815
Name: C, dtype: float64

## Tworzenie/usuwanie kolumn/wierszy

### Tworzenie nowej kolumny

In [ ]:
df['new2'] = 'AA'
df

           A         B         C         D       new new2
W0 -1.464134  1.239321  0.121756  0.131893 -0.224813   AA
W1 -0.219985  0.676829  0.584892 -0.405147  0.456844   AA
W2  0.482510 -1.181670  1.633778 -2.511288 -0.699160   AA
W3 -1.511729  0.025677  0.373815 -0.811521 -1.486052   AA
W4 -0.620976 -1.779730 -0.340072 -1.737196 -2.400706   AA

#### Usuwanie kolumny

In [ ]:
df.drop('new', axis=1)

           A         B         C         D new2
W0 -1.464134  1.239321  0.121756  0.131893   AA
W1 -0.219985  0.676829  0.584892 -0.405147   AA
W2  0.482510 -1.181670  1.633778 -2.511288   AA
W3 -1.511729  0.025677  0.373815 -0.811521   AA
W4 -0.620976 -1.779730 -0.340072 -1.737196   AA

In [ ]:
df

           A         B         C         D       new new2
W0 -1.464134  1.239321  0.121756  0.131893 -0.224813   AA
W1 -0.219985  0.676829  0.584892 -0.405147  0.456844   AA
W2  0.482510 -1.181670  1.633778 -2.511288 -0.699160   AA
W3 -1.511729  0.025677  0.373815 -0.811521 -1.486052   AA
W4 -0.620976 -1.779730 -0.340072 -1.737196 -2.400706   AA

In [ ]:
df.drop('new', axis=1, inplace=True)

In [ ]:
df

           A         B         C         D new2
W0 -1.464134  1.239321  0.121756  0.131893   AA
W1 -0.219985  0.676829  0.584892 -0.405147   AA
W2  0.482510 -1.181670  1.633778 -2.511288   AA
W3 -1.511729  0.025677  0.373815 -0.811521   AA
W4 -0.620976 -1.779730 -0.340072 -1.737196   AA

### Wycinanie kolumny
`pop()` – usuwa jedną kolumnę i zwraca ją jako Series

In [ ]:
df.pop('B') # inplace

W0    1.239321
W1    0.676829
W2   -1.181670
W3    0.025677
W4   -1.779730
Name: B, dtype: float64

In [ ]:
df

           A         C         D new2
W0 -1.464134  0.121756  0.131893   AA
W1 -0.219985  0.584892 -0.405147   AA
W2  0.482510  1.633778 -2.511288   AA
W3 -1.511729  0.373815 -0.811521   AA
W4 -0.620976 -0.340072 -1.737196   AA

### Usuwanie wierszy

In [ ]:
df.drop('W0', axis=0)

           A         C         D
W1 -0.932904  0.410316 -2.079916
W2  0.243280 -0.273260  0.382081
W3  0.521342  0.380153 -1.644616
W4  0.275425  0.516446  0.447643

In [ ]:
df

           A         C         D
W0  0.366845 -0.251625 -0.449224
W1 -0.932904  0.410316 -2.079916
W2  0.243280 -0.273260  0.382081
W3  0.521342  0.380153 -1.644616
W4  0.275425  0.516446  0.447643

In [ ]:
df.drop('W0', axis=0, inplace=True)

In [ ]:
df

           A         C         D new2
W1 -0.219985  0.584892 -0.405147   AA
W2  0.482510  1.633778 -2.511288   AA
W3 -1.511729  0.373815 -0.811521   AA
W4 -0.620976 -0.340072 -1.737196   AA

### Resetowanie indeksów

In [ ]:
df.reset_index()

  index         A         C         D new2
0    W1 -0.219985  0.584892 -0.405147   AA
1    W2  0.482510  1.633778 -2.511288   AA
2    W3 -1.511729  0.373815 -0.811521   AA
3    W4 -0.620976 -0.340072 -1.737196   AA

In [ ]:
df.reset_index(drop=True)

          A         C         D new2
0 -0.219985  0.584892 -0.405147   AA
1  0.482510  1.633778 -2.511288   AA
2 -1.511729  0.373815 -0.811521   AA
3 -0.620976 -0.340072 -1.737196   AA

In [ ]:
df

           A         C         D new2
W1 -0.219985  0.584892 -0.405147   AA
W2  0.482510  1.633778 -2.511288   AA
W3 -1.511729  0.373815 -0.811521   AA
W4 -0.620976 -0.340072 -1.737196   AA

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df

          A         C         D new2
0 -0.219985  0.584892 -0.405147   AA
1  0.482510  1.633778 -2.511288   AA
2 -1.511729  0.373815 -0.811521   AA
3 -0.620976 -0.340072 -1.737196   AA

In [ ]:
# nowe indeksy
newind = 'CA NY WY OR'.split() #.split() dzieli tekst po spacjach i zwraca listę słów.
newind

['CA', 'NY', 'WY', 'OR']

In [ ]:
df['States'] = newind
df

          A         C         D new2 States
0 -0.219985  0.584892 -0.405147   AA     CA
1  0.482510  1.633778 -2.511288   AA     NY
2 -1.511729  0.373815 -0.811521   AA     WY
3 -0.620976 -0.340072 -1.737196   AA     OR

In [ ]:
df.set_index('States', inplace=True)

In [ ]:
df

               A         C         D new2
States
CA     -0.219985  0.584892 -0.405147   AA
NY      0.482510  1.633778 -2.511288   AA
WY     -1.511729  0.373815 -0.811521   AA
OR     -0.620976 -0.340072 -1.737196   AA

## Braki danych

In [ ]:
# Tworzenie przykładowej ramki danych z brakującymi danymi
data = {'A': [1, 2, np.nan, 4, np.nan],
        'B': [5, np.nan, np.nan, 8, 9],
        'C': [np.nan, 12, 13, np.nan, 15],
        'D': [12, 12, 13, 12, 15]}
df = pd.DataFrame(data)

df

     A    B     C   D
0  1.0  5.0   NaN  12
1  2.0  NaN  12.0  12
2  NaN  NaN  13.0  13
3  4.0  8.0   NaN  12
4  NaN  9.0  15.0  15

### Usuwanie braków

In [ ]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
df.dropna(axis=1)

    D
0  12
1  12
2  13
3  12
4  15

In [ ]:
df.dropna(thresh=3)

     A    B     C   D
0  1.0  5.0   NaN  12
1  2.0  NaN  12.0  12
3  4.0  8.0   NaN  12
4  NaN  9.0  15.0  15

### Uzupełnianie braków dowolną wartością

In [ ]:
df

     A    B     C   D
0  1.0  5.0   NaN  12
1  2.0  NaN  12.0  12
2  NaN  NaN  13.0  13
3  4.0  8.0   NaN  12
4  NaN  9.0  15.0  15

In [ ]:
df.fillna(value='FILL VALUE')

            A           B           C   D
0         1.0         5.0  FILL VALUE  12
1         2.0  FILL VALUE        12.0  12
2  FILL VALUE  FILL VALUE        13.0  13
3         4.0         8.0  FILL VALUE  12
4  FILL VALUE         9.0        15.0  15

### Uzupełnienie braków średnią wartością dla każdej kolumny

In [ ]:

df_mean = df.fillna(df.mean())

df_mean

          A         B          C   D
0  1.000000  5.000000  13.333333  12
1  2.000000  7.333333  12.000000  12
2  2.333333  7.333333  13.000000  13
3  4.000000  8.000000  13.333333  12
4  2.333333  9.000000  15.000000  15

### Uzupełnienie braków wartościami sąsiednimi (interpolacja liniowa)

In [ ]:

df_interpolated = df.interpolate(method='linear')
# interpolate() może nie uzupełnić braku wartości dla pierwszego wiersza,
# gdyż nie ma on poprzedniej wartości, od której można by interpolować

df_interpolated

     A    B     C   D
0  1.0  5.0   NaN  12
1  2.0  6.0  12.0  12
2  3.0  7.0  13.0  13
3  4.0  8.0  14.0  12
4  4.0  9.0  15.0  15

In [ ]:
# Uzupełnienie braków wartościami 0
df_zero = df.fillna(0)
df_zero

     A    B     C   D
0  1.0  5.0   0.0  12
1  2.0  0.0  12.0  12
2  0.0  0.0  13.0  13
3  4.0  8.0   0.0  12
4  0.0  9.0  15.0  15

### Uzupełnianie sąsiednią wartością

In [ ]:
# Wypełnienie braków ostatnią znaną wartością
df_back= df.ffill()
df_back

     A    B     C
0  1.0  5.0   NaN
1  2.0  5.0  12.0
2  2.0  5.0  13.0
3  4.0  8.0  13.0
4  4.0  9.0  15.0

In [ ]:
# Wypełnienie braków następną znaną wartością
df_next = df.bfill()
df_next

     A    B     C   D
0  1.0  5.0  12.0  12
1  2.0  8.0  12.0  12
2  4.0  8.0  13.0  13
3  4.0  8.0  15.0  12
4  NaN  9.0  15.0  15

## Groupby

Metoda `groupby` pozwala pogrupować wiersze danych razem i wywołać funkcje agregujące.

In [ ]:
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

Teraz można użyć metody `.groupby()`, aby grupować wiersze na podstawie nazwy kolumny. Na przykład grupujmy na podstawie Company. Spowoduje to utworzenie obiektu DataFrameGroupBy:

In [ ]:
df.groupby('Company')

In [ ]:
df.groupby("Company")['Sales'].mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

Można zapisać ten obiekt jako nową zmienną

In [ ]:
by_comp = df.groupby("Company")['Sales']

In [ ]:
by_comp

I wywołać np. metodę `mean` na tym obiekcie

In [ ]:
by_comp.mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

Więcej metod:

In [ ]:
by_comp.std()

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sales, dtype: float64

In [ ]:
by_comp.min()

Company
FB      243
GOOG    120
MSFT    124
Name: Sales, dtype: int64

In [ ]:
by_comp.max()

Company
FB      350
GOOG    200
MSFT    340
Name: Sales, dtype: int64

In [ ]:
by_comp.count()

Company
FB      2
GOOG    2
MSFT    2
Name: Sales, dtype: int64

In [ ]:
by_comp.describe()

         count   mean         std    min     25%    50%     75%    max
Company
FB         2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG       2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT       2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [ ]:
df.groupby('Company').value_counts()

Company  Person   Sales
FB       Carl     243      1
         Sarah    350      1
GOOG     Charlie  120      1
         Sam      200      1
MSFT     Amy      340      1
         Vanessa  124      1
Name: count, dtype: int64

In [ ]:
df.groupby('Company').count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

## Scalanie, Łączenie i Konkatenacja
Istnieją trzy główne sposoby **łączenia obiektów** DataFrame: **scalanie (merging), łączenie (joining)** oraz **konkatenacja (concatenating)**.

____

Przykładowe ramki danych

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [ ]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [ ]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

### Konkatenacja
Konkatenacja to w zasadzie „sklejanie” ze sobą DataFrame’ów. Pamiętaj, że wymiary muszą się zgadzać wzdłuż osi, po której dokonujesz konkatenacji.
Możesz użyć funkcji pd.concat i przekazać do niej listę DataFrame’ów, które chcesz połąc

In [ ]:
pd.concat([df1,df2,df3]) #sklejanie tabel jedna pod drugą

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3],axis=1) #sklejanie tabel obok siebie

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

### Łączenie (Merging)
Funkcja `merge` pozwala na łączenie DataFrame’ów przy użyciu logiki podobnej do tej, jaką stosuje się przy łączeniu tabel w SQL.

Nowe przykładowe ramki danych

In [ ]:
df1=pd.DataFrame({'animal':['dog', 'cat', 'pig', 'cow'],
                  'age':[5,3,6,2]})
df2=pd.DataFrame({'animal':['dog', 'parrot', 'pig', 'cow', 'horse'],
                  'eat':[2,2,3,5,2]})

In [ ]:
df1

  animal  age
0    dog    5
1    cat    3
2    pig    6
3    cow    2

In [ ]:
df2

   animal  eat
0     dog    2
1  parrot    2
2     pig    3
3     cow    5
4   horse    2

In [ ]:
pd.merge(df1, df2, on='animal', how='inner')  #część wspólna

  animal  age  eat
0    dog    5    2
1    pig    6    3
2    cow    2    5

In [ ]:
pd.merge(df1, df2, on='animal', how='left') #do lewej tabeli

  animal  age  eat
0    dog    5  2.0
1    cat    3  NaN
2    pig    6  3.0
3    cow    2  5.0

In [ ]:
pd.merge(df1, df2, on='animal', how='right')  #do prawej tabeli

   animal  age  eat
0     dog  5.0    2
1  parrot  NaN    2
2     pig  6.0    3
3     cow  2.0    5
4   horse  NaN    2

In [ ]:
pd.merge(df1, df2, on='animal', how='outer')  #wszystkie rekordy z obu tabel

   animal  age  eat
0     cat  3.0  NaN
1     cow  2.0  5.0
2     dog  5.0  2.0
3   horse  NaN  2.0
4  parrot  NaN  2.0
5     pig  6.0  3.0

In [ ]:
pd.merge(df1, df2, on='animal', how='left').dropna()

  animal  age  eat
0    dog    5  2.0
2    pig    6  3.0
3    cow    2  5.0

### Łączenie (Joining)
Łączenie to wygodna metoda łączenia kolumn z dwóch DataFrame’ów, które mogą mieć różne indeksy, w jeden wspólny DataFrame jako wynik.

Czyli: scalasz dane po indeksach, a nie po konkretnych kolumnach jak przy merge.

In [ ]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2'])

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
left

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [ ]:
right

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [ ]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [ ]:
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

## Wybrane operacje
W pandasach dostępnych jest wiele przydatnych operacji, które trudno przypisać do jednej konkretnej grupy. W tej sekcji przedstawimy kilka z nich.

In [ ]:
df = pd.DataFrame({'col1':[1,2,3,4,5,6,7,8,9,10],
                   'col2':[444,555,666,444,777,888,999,888,999,444],
                   'col3':['abc','def','ghi','ghi','def','def','tuw','xyz','abc','abc']})
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  ghi
4     5   777  def
5     6   888  def
6     7   999  tuw
7     8   888  xyz
8     9   999  abc
9    10   444  abc

### head

In [ ]:
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  ghi
4     5   777  def

In [ ]:
df.head(3)

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi

### tail

In [ ]:
df.tail()

   col1  col2 col3
5     6   888  def
6     7   999  tuw
7     8   888  xyz
8     9   999  abc
9    10   444  abc

In [ ]:
df.tail(2)

   col1  col2 col3
8     9   999  abc
9    10   444  abc

### sample

In [ ]:
df.sample()

   col1  col2 col3
4     5   777  def

In [ ]:
df.sample(3)

   col1  col2 col3
5     6   888  def
2     3   666  ghi
8     9   999  abc

### Informacje o unikalnych wartościach

In [ ]:
df.head(3)

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi

In [ ]:
df['col2'].unique()

array([444, 555, 666, 777, 888, 999])

In [ ]:
df['col2'].nunique()

6

In [ ]:
df.nunique()

col1    10
col2     6
col3     5
dtype: int64

In [ ]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  ghi
4     5   777  def
5     6   888  def
6     7   999  tuw
7     8   888  xyz
8     9   999  abc
9    10   444  abc

In [ ]:
df['col2'].value_counts()

col2
444    3
999    2
888    2
555    1
777    1
666    1
Name: count, dtype: int64

### Wybieranie danych

In [ ]:
#Select from DataFrame using criteria from multiple columns
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [ ]:
newdf

   col1  col2 col3
3     4   444  ghi
9    10   444  abc

### Funkcja ```aplay```

In [ ]:
def times2(x):
    return x*2

In [ ]:
df['col1'].apply(times2)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
9    20
Name: col1, dtype: int64

In [ ]:
df.head(3)

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi

In [ ]:
df['col4']=df['col1'].apply(times2)

In [ ]:
df.head(3)

   col1  col2 col3  col4
0     1   444  abc     2
1     2   555  def     4
2     3   666  ghi     6

### Pobieranie nazw kolumn i indeksów

In [ ]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    10 non-null     int64
 1   col2    10 non-null     int64
 2   col3    10 non-null     object
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

### Sortowanie danych

In [ ]:
df

   col1  col2 col3  col4
0     1   444  abc     2
1     2   555  def     4
2     3   666  ghi     6
3     4   444  ghi     8
4     5   777  def    10
5     6   888  def    12
6     7   999  tuw    14
7     8   888  xyz    16
8     9   999  abc    18
9    10   444  abc    20

In [ ]:
df.sort_values(by='col2') #inplace=False by default

   col1  col2 col3
0     1   444  abc
3     4   444  ghi
9    10   444  abc
1     2   555  def
2     3   666  ghi
4     5   777  def
7     8   888  xyz
5     6   888  def
6     7   999  tuw
8     9   999  abc

In [ ]:
df.sort_values(by='col2',ascending=False) # malejąco

   col1  col2 col3
6     7   999  tuw
8     9   999  abc
5     6   888  def
7     8   888  xyz
4     5   777  def
2     3   666  ghi
1     2   555  def
0     1   444  abc
3     4   444  ghi
9    10   444  abc

### Znajdowaie/Sporawdzanie wartości Null Values

In [ ]:
df.isnull()

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

### Pivot table

In [ ]:
df

   col1  col2 col3  col4
0     1   444  abc     2
1     2   555  def     4
2     3   666  ghi     6
3     4   444  ghi     8
4     5   777  def    10
5     6   888  def    12
6     7   999  tuw    14
7     8   888  xyz    16
8     9   999  abc    18
9    10   444  abc    20

In [ ]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [ ]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN



## Wczytywanie/Zapisywanie danych

### Pobieranie zbiorów danych z GitHub

In [ ]:
!git clone https://github.com/matzim95/ML-datasets

Cloning into 'ML-datasets'...
remote: Enumerating objects: 201, done.
remote: Counting objects: 100% (141/141), done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 201 (delta 35), reused 124 (delta 24), pack-reused 60 (from 1)
Receiving objects: 100% (201/201), 35.87 MiB | 13.17 MiB/s, done.
Resolving deltas: 100% (47/47), done.

### Montowanie dysku google i wczytywanie z dysku pliki

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls '/content/drive/MyDrive'

ls: cannot access '/content/drive/MyDrive': No such file or directory

In [ ]:
!ls "/content/drive/MyDrive/Colab Notebooks"


Pandas potrafi czytać różne typy plików za pomocą metod rozpoczynających się od `pd.read_`. Przyjrzyjmy się najczęściej spotykanym:

### CSV

#### pd.read_csv
Najważniejsze argumenty:
- ścieżka do pliku
- separator kolumn (domyślnie przecinek)
- nagłówki (header=True)
- indeksy
- nazwy kolumn

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/insuranceSAD.csv')
df.head(3)

   Unnamed: 0  age    bmi  children  smoker     charges  female
0           0   19  27.90         0       1  16884.9240       1
1           1   18  33.77         1       0   1725.5523       0
2           2   28  33.00         3       0   4449.4620       0

In [ ]:
titanic = pd.read_csv('ML-datasets/titanic.csv')
titanic.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
titanic = pd.read_csv('ML-datasets/titanic.csv', sep=';')
titanic.head(3)

  PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0  1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/...
1  2,1,1,"Cumings, Mrs. John Bradley (Florence Br...
2  3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,S...

In [ ]:
df = pd.read_csv('example.csv')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

#### to_csv

In [ ]:
df.to_csv('example_out.csv',index=False)

### Excel

#### pd.read_excel

In [ ]:
df = pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')
df.head(3)

   Unnamed: 0  a  b   c   d
0           0  0  1   2   3
1           1  4  5   6   7
2           2  8  9  10  11

#### to_excel

In [ ]:
df.to_excel('Excel_Sample_out.xlsx',sheet_name='Sheet1')